import type { EntityPaletteItemSpec, NodeFamilySpec } from '@dialogram/shared';
/**
 * Neutral runtime options the source-model storage (and tool palette) need.
 *
 * These are the only product-shaped values core still reads directly: the VS Code settings
 * namespace to look configuration up under, and the operation-prefix string carried to the client
 * on the graph model (so the client can tell which language runtime produced the diagram). Both are
 * supplied as plain data by the consuming extension — core hardcodes NO product literals.
 */
export interface StorageRuntimeOptions {
    /** VS Code settings namespace (e.g. the `xxxLang` configuration section). */
    settingsNamespace: string;
    /** Operation-prefix identifier surfaced to the client on the graph model root args. */
    operationPrefix: string;
    /**
     * Selects the alternate entity-palette layout (a reduced entity vocabulary) instead of the
     * default one. Supplied by the consuming extension; core hardcodes no product discriminator.
     */
    useAlternateEntityPalette?: boolean;
    /**
     * Extra entries for the Entities palette, contributed by the product.
     *
     * Plain data on purpose. The two lists above are the platform's own, and a
     * product cannot add to them without editing that file — which is how a
     * neutral platform ends up learning every product's vocabulary. A profile
     * describes an entry instead, and the platform builds it.
     */
    entityPaletteItems?: EntityPaletteItemSpec[];
    /**
     * The node families the product recognises — see `NodeFamilySpec`.
     * The class is derived from each annotation, so core names none.
     */
    nodeFamilies?: NodeFamilySpec[];
    /**
     * Whether the tool palette offers anything to create. Default `true`.
     *
     * `false` empties it — the platform's Entities/Ports/Connections categories
     * AND {@link entityPaletteItems}. The palette was append-only until now: a
     * product could add an entry and never remove one, which is the wrong shape
     * for a diagram that is a projection of a source artifact. Such a diagram is
     * generated by reading a file, so a creation tool has nowhere to write; the
     * entries are inert at best, and read as a promise the diagram cannot keep.
     *
     * The suppression covers the product's own contributions deliberately. A
     * projection that has nothing to create has nothing of its own to create
     * either, and a flag that left a product's entries standing would leave the
     * palette in the exact state the flag exists to prevent.
     */
    supportsElementCreation?: boolean;
}

export const STORAGE_RUNTIME_OPTIONS = Symbol('StorageRuntimeOptions');
